import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { mkdtempSync, rmSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { createMcpServer } from '../src/server.mjs';
import { Reader } from '../src/core.mjs';
import { Writer } from '../src/writer.mjs';
import { fixtures, fixtureAccess } from './fixtures.mjs';
const provider=fixtures();
if(process.argv.includes('--fail')) provider.chat=async()=>{throw new Error('SECRET_FIXTURE_DO_NOT_LEAK');};
const writeMode=process.argv.includes('--writer');
const scopes=writeMode?['whatsapp.read','whatsapp.send','whatsapp.group.create','whatsapp.group.manage']:null;
const access=fixtureAccess(undefined,scopes);
const reader=new Reader(provider,{access,cooldownMs:0});
const stateDirectory=writeMode?mkdtempSync(path.join(tmpdir(),'wa-mcp-writer-')):null;
if(stateDirectory) process.once('exit',()=>{try{rmSync(stateDirectory,{recursive:true,force:true});}catch{}});
const writer=writeMode?new Writer(provider,{access,stateDirectory}):null;
const server=createMcpServer(reader,writer);
await server.connect(new StdioServerTransport());
